image: python:3.12-slim

stages:
  - test

unit-test:
  stage: test
  variables:
    APP_MODE: demo
  before_script:
    - apt-get update
    - apt-get install --yes --no-install-recommends make nodejs npm
    - make install
  script:
    - make test
