from enum import StrEnum


class PublicErrorCode(StrEnum):
    INPUT_EMPTY = "INPUT_EMPTY"
    INPUT_TOO_LARGE = "INPUT_TOO_LARGE"
    LINE_LIMIT_EXCEEDED = "LINE_LIMIT_EXCEEDED"
    INVALID_UTF8 = "INVALID_UTF8"
    INVALID_DIFF_FORMAT = "INVALID_DIFF_FORMAT"
    RATE_LIMITED = "RATE_LIMITED"
    AI_NOT_CONFIGURED = "AI_NOT_CONFIGURED"
    AI_TIMEOUT = "AI_TIMEOUT"
    AI_AUTH_FAILED = "AI_AUTH_FAILED"
    AI_INVALID_RESPONSE = "AI_INVALID_RESPONSE"
    INTERNAL_ERROR = "INTERNAL_ERROR"
